# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [7]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [8]:
weather_data = pd.read_csv("output/world_cities.csv")
weather_data.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Vendas Novas,38.6771,-8.4579,292.27,91,25,1.65,PT,1631420862
1,Arlit,18.7369,7.3853,306.41,19,11,1.98,NE,1631420863
2,Santa Cruz de la Sierra,-17.8000,-63.1667,296.85,73,4,6.69,BO,1631420691
3,Montepuez,-13.1256,38.9997,291.96,78,0,3.43,MZ,1631420865
4,Cockburn Town,21.4612,-71.1419,301.68,76,63,9.28,TC,1631420866

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [11]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [46]:
# Step 1: Store latitude and longitude in locations
locations = weather_data[["Lat", "Lng"]]

# Fill NaN values and convert to float
humidity = weather_data["Humidity"].astype(float)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, 
                                 dissipating = True, max_intensity = 100,
                                 point_radius = 10)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [35]:
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.
cleaned_weather_data = weather_data.loc[(weather_data["Max Temp"] < 299.817) & 
                                        (weather_data["Max Temp"] > 294.261) &
                                        (weather_data["Wind Speed"] < 10) & 
                                        (weather_data["Cloudiness"] == 0)]

cleaned_weather_data

# # Step 1: Store latitude and longitude in locations
# locations = cleaned_weather_data[["Lat", "Lng"]]

# # Fill NaN values and convert to float
# humidity = cleaned_weather_data["Humidity"].astype(float)

# # Plot Heatmap
# fig_cleaned_weather = gmaps.figure()

# # Create heat layer
# heat_layer_cleaned_weather = gmaps.heatmap_layer(locations, weights = humidity, 
#                                  dissipating = True, max_intensity = 100,
#                                  point_radius = 10)


# # Add layer
# fig_cleaned_weather.add_layer(heat_layer_cleaned_weather)

# # Display figure
# fig_cleaned_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
40,Geraldton,-28.7667,114.6000,294.38,35,0,4.63,AU,1631420912
56,Karpathos,35.5070,27.2132,295.13,73,0,7.20,GR,1631420935
97,Licata,37.1071,13.9461,295.67,73,0,2.77,IT,1631421494
125,Zhangaözen,43.3000,52.8000,296.41,25,0,4.38,KZ,1631421530
130,Nālūt,30.3333,10.8500,296.92,59,0,5.81,LY,1631421536
233,Carnarvon,-24.8667,113.6333,298.19,20,0,7.20,AU,1631421634
251,Coração de Jesus,-16.6853,-44.3650,294.55,30,0,4.38,BR,1631421687
254,Noumea,-22.2763,166.4572,299.14,56,0,7.82,NC,1631421692
357,Bereket,39.2446,55.5154,298.88,11,0,9.22,TM,1631421827
384,Yulara,-25.2406,130.9889,299.06,21,0,6.17,AU,1631421863
429,Dawlatabad,36.4141,64.9053,297.56,12,0,2.29,AF,1631421920
439,San Quintín,30.4833,-115.9500,296.12,82,0,4.45,MX,1631421933
445,Birecik,37.0294,37.9903,295.71,54,0,1.99,TR,1631421940
446,Assiut,27.1810,31.1837,295.25,57,0,4.88,EG,1631421941
523,Havelock,34.8791,-76.9013,295.34,92,0,1.20,US,1631421758
540,Teguise,29.0605,-13.5640,294.27,83,0,2.06,ES,1631422060
594,Marrakesh,31.6315,-8.0083,296.19,56,0,1.03,MA,1631421967
625,Moindou,-21.6924,165.6770,299.12,59,0,5.78,NC,1631422174

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [45]:
hotel_df = cleaned_weather_data
hotel_df["Hotel Name"] = ""

<ipython-input-45-9f9d8e2703c2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ""

In [60]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
hotel_info
city_locations = hotel_df[["Lat", "Lng"]]
humidity = hotel_df["Humidity"]

In [62]:
# Add marker layer ontop of heat map
# Display figure
fig = gmaps.figure()
# Create heat layer
heat_layer = gmaps.heatmap_layer(city_locations, weights = humidity, 
                                 dissipating = True, max_intensity = 100,
                                 point_radius = 10)
# Add layer
fig.add_layer(heat_layer)
markers = gmaps.marker_layer(city_locations, info_box_content = hotel_info)
fig.add_layer(markers)

fig

Figure(layout=FigureLayout(height='420px'))